"""Render results/eval.json into README.md between the RESULTS markers.

Usage: uv run python scripts/report.py [--eval results/eval.json] [--readme README.md]
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

START = "<!-- RESULTS:START -->"
END = "<!-- RESULTS:END -->"


def _cell(metric: dict[str, Any]) -> str:
    lo, hi = metric["ci95"]
    return f"{metric['mean']:.3f} <sub>[{lo:.3f}, {hi:.3f}]</sub>"


def _table(rows: dict[str, dict[str, Any]], label: str) -> list[str]:
    lines = [
        f"| {label} | n | MRR@10 | Recall@1 | Recall@5 | Recall@10 | p50 latency |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for name, s in rows.items():
        lines.append(
            f"| `{name}` | {s['n_queries']} | {_cell(s['mrr@10'])} | {_cell(s['recall@1'])} | "
            f"{_cell(s['recall@5'])} | {_cell(s['recall@10'])} | "
            f"{s['latency_ms']['p50']:.1f} ms |"
        )
    return lines


def render(report: dict[str, Any]) -> str:
    cfg = report["config"]
    results = report["results"]
    out = [
        f"_Generated by `scripts/report.py` from `results/eval.json` "
        f"({report['generated_at']}). Embedder `{cfg['embedder']}`, reranker "
        f"`{cfg['reranker']}` (top {cfg['rerank_depth']} of the hybrid list). "
        f"Brackets are 95% bootstrap CIs over queries "
        f"({cfg['bootstrap']['resamples']} resamples)._",
        "",
        "**All queries (both repos pooled)**",
        "",
        *_table({m: r["overall"] for m, r in results.items()}, "mode"),
    ]
    for repo in report["repos"]:
        name = repo["name"]
        out += [
            "",
            f"**{name}** @ `{repo['ref']}` ({repo['commit'][:12]}): {repo['chunks']} chunks, "
            f"{repo['queries']} queries ({repo['dropped_duplicate_query']} dropped as "
            f"duplicate docstrings, {repo['dropped_verbatim_in_index']} dropped as verbatim "
            f"in the index)",
            "",
            *_table({m: r["per_repo"][name] for m, r in results.items()}, "mode"),
        ]
    emb = report.get("query_embedding_latency_ms") or {}
    if emb.get("p50") is not None:
        out += [
            "",
            f"Latency is retrieval-only with the query vector precomputed; one query "
            f"embedding call to local Ollama added a further p50 of {emb['p50']:.0f} ms "
            f"(n={emb['n']}, measured on a shared machine).",
        ]
    return "\n".join(out)


def update_readme(readme: str, block: str) -> str:
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if not pattern.search(readme):
        raise SystemExit(f"README is missing the {START} / {END} markers")
    return pattern.sub(lambda _m: f"{START}\n{block}\n{END}", readme)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--eval", type=Path, default=Path("results/eval.json"))
    parser.add_argument("--readme", type=Path, default=Path("README.md"))
    args = parser.parse_args()
    report = json.loads(args.eval.read_text())
    args.readme.write_text(update_readme(args.readme.read_text(), render(report)))
    print(f"updated {args.readme}")


if __name__ == "__main__":
    main()
