"""Render results/eval.json into README.md between the RESULTS markers.

Usage: uv run python scripts/report.py [--eval results/eval.json] [--readme README.md]
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

START = "<!-- RESULTS:START -->"
END = "<!-- RESULTS:END -->"


def _cell(metric: dict[str, Any]) -> str:
    lo, hi = metric["ci95"]
    return f"{metric['mean']:.3f} <sub>[{lo:.3f}, {hi:.3f}]</sub>"


def _table(rows: dict[str, dict[str, Any]], label: str) -> list[str]:
    lines = [
        f"| {label} | n | MRR@10 | Recall@1 | Recall@5 | Recall@10 | p50 latency |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for name, s in rows.items():
        lines.append(
            f"| `{name}` | {s['n_queries']} | {_cell(s['mrr@10'])} | {_cell(s['recall@1'])} | "
            f"{_cell(s['recall@5'])} | {_cell(s['recall@10'])} | "
            f"{s['latency_ms']['p50']:.1f} ms |"
        )
    return lines


def render(report: dict[str, Any]) -> str:
    cfg = report["config"]
    results = report["results"]
    out = [
        f"_Generated by `scripts/report.py` from `results/eval.json` "
        f"({report['generated_at']}). Embedder `{cfg['embedder']}`, reranker "
        f"`{cfg['reranker']}` (top {cfg['rerank_depth']} of the hybrid list). "
        f"Brackets are 95% bootstrap CIs over queries "
        f"({cfg['bootstrap']['resamples']} resamples)._",
        "",
        "**All queries (both repos pooled)**",
        "",
        *_table({m: r["overall"] for m, r in results.items()}, "mode"),
    ]
    for repo in report["repos"]:
        name = repo["name"]
        out += [
            "",
            f"**{name}** @ `{repo['ref']}` ({repo['commit'][:12]}): {repo['chunks']} chunks, "
            f"{repo['queries']} queries ({repo['dropped_duplicate_query']} dropped as "
            f"duplicate docstrings, {repo['dropped_verbatim_in_index']} dropped as verbatim "
            f"in the index)",
            "",
            *_table({m: r["per_repo"][name] for m, r in results.items()}, "mode"),
        ]
    comparisons = report.get("paired_comparisons") or {}
    if comparisons:
        out += [
            "",
            "**Paired differences in MRR@10** (same queries, paired bootstrap 95% CI; "
            "wins/losses count queries where one mode ranked the target strictly higher)",
            "",
            "| comparison | ΔMRR@10 | 95% CI | wins / losses |",
            "|---|---:|---:|---:|",
        ]
        for name, c in comparisons.items():
            lo, hi = c["ci95"]
            out.append(
                f"| {name} | {c['mrr@10_diff']:+.3f} | [{lo:+.3f}, {hi:+.3f}] | "
                f"{c['a_better']} / {c['b_better']} |"
            )
    model = report.get("model_latency_ms") or {}
    if model.get("query_embedding_p50") is not None:
        rerank = model.get("rerank_call_p50")
        rerank_txt = (
            f" and one uncached cross-encoder call over {model['rerank_candidates_per_call']} "
            f"candidates took p50 {rerank:.0f} ms"
            if rerank is not None
            else ""
        )
        warm = (
            "Latency above is retrieval only: query embeddings are batched up front and "
            "every cross-encoder score came from the on-disk cache of an earlier run."
            if model.get("uncached_rerank_pairs_in_timed_loop") == 0
            else "Latency above excludes query embedding (batched up front) but includes "
            "cross-encoder calls."
        )
        out += [
            "",
            f"{warm} Measured separately (n={model['n']}), one uncached query embedding took "
            f"p50 {model['query_embedding_p50']:.0f} ms{rerank_txt}. These were measured on "
            f"a heavily loaded, swapping laptop with a shared Ollama server, so treat them "
            f"as upper bounds.",
        ]
    return "\n".join(out)


def update_readme(readme: str, block: str) -> str:
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if not pattern.search(readme):
        raise SystemExit(f"README is missing the {START} / {END} markers")
    return pattern.sub(lambda _m: f"{START}\n{block}\n{END}", readme)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--eval", type=Path, default=Path("results/eval.json"))
    parser.add_argument("--readme", type=Path, default=Path("README.md"))
    args = parser.parse_args()
    report = json.loads(args.eval.read_text())
    args.readme.write_text(update_readme(args.readme.read_text(), render(report)))
    print(f"updated {args.readme}")


if __name__ == "__main__":
    main()
